### ISSUE TITLE
CRC-16 not getting expected result...

### ISSUE THREAD

**Issue by APayerl** [d-bahr/CRCpp#13]
I have a hex string that gives this row on this website CRC calculator: https://crccalc.com/
![image](https://user-images.githubusercontent.com/6882326/146067149-3e9be0d0-59ab-45ed-b7f2-bf6a3f6e017f.png)

But when I used the values from that website to check the same hexadecimal string with your library, I got a different answer... What am I doing wrong? (I'm new to CRC:s....)

The first and third output is same and second and fourth is also same.

```
std::cout << std::hex << calcCRC(s, CRC::CRC_16_X25()) << std::endl;
std::cout << calcCRC(hex_str_to_bin_str(s), CRC::CRC_16_X25()) << std::endl;

static const CRC::Parameters<uint16_t, 16> parameters = { 0x1021, 0xFFFF, 0xFFFF, true, true };
std::cout << std::hex << calcCRC(s, parameters) << std::endl;
std::cout << calcCRC(hex_str_to_bin_str(s), parameters) << std::endl;
```

My string is as follows:
`A11D01000110B0AEE6E7000F4000000000022409060100000281FF09074B464D5F30303109060000600100FF09103733343031353730333035343234373609060000600107FF09074D41333034483409060100010700FF060000000309060100020700FF060000000009060100030700FF060000000009060100040700FF0600000000090601001F0700FF060000002009060100330700FF060000000009060100470700FF060000000009060100200700FF060000091209060100340700FF060000000009060100480700FF060000000009060000010000FF090C07E5031702123200FFFFC40009060100010800FF060000047609060100020800FF060000000009060100030800FF060000004309060100040800FF0600000000`

The functions mentioned are pretty basic...
```
const char* hex_char_to_bin(char c)
{
    switch(toupper(c))
    {
        case '0': return "0000";
        case '1': return "0001";
        case '2': return "0010";
        case '3': return "0011";
        case '4': return "0100";
        case '5': return "0101";
        case '6': return "0110";
        case '7': return "0111";
        case '8': return "1000";
        case '9': return "1001";
        case 'A': return "1010";
        case 'B': return "1011";
        case 'C': return "1100";
        case 'D': return "1101";
        case 'E': return "1110";
        case 'F': return "1111";
    }
}

std::string hex_str_to_bin_str(const std::string& hex)
{
    std::string bin;
    for(unsigned i = 0; i != hex.length(); ++i)
       bin += hex_char_to_bin(hex[i]);
    return bin;
}

std::uint16_t calcCRC(std::string s, CRC::Parameters<uint16_t, (uint16_t)16U> params) {
    auto table = params.MakeTable();
    return CRC::Calculate(s.c_str(), s.length(), table);
}
```

**Comment by d-bahr** [comment]
Hello,

I think there's a misunderstanding about the input format that `CRC::Calculate` expects. From the code you posted, it looks like you are writing the data as a string of bits. However, `CRC::Calculate` requires binary data in raw form, such as one might have with `std::vector<uint8_t>`.

I was able to produce the same value as https://crccalc.com/ by modifying your code to properly convert from hex to binary:

```
uint8_t hex_char_to_bin(char c)
{
	switch (toupper(c))
	{
	case '0': return 0x00;
	case '1': return 0x01;
	case '2': return 0x02;
	case '3': return 0x03;
	case '4': return 0x04;
	case '5': return 0x05;
	case '6': return 0x06;
	case '7': return 0x07;
	case '8': return 0x08;
	case '9': return 0x09;
	case 'A': return 0x0A;
	case 'B': return 0x0B;
	case 'C': return 0x0C;
	case 'D': return 0x0D;
	case 'E': return 0x0E;
	case 'F': return 0x0F;
	}
}

std::string hex_str_to_bin_str(const std::string& hex)
{
	std::string bin;
	for (unsigned i = 0; i + 1 < hex.length(); i += 2)
	{
		uint8_t byte;
		// Upper nibble
		byte = hex_char_to_bin(hex[i]) << 4;
		// Lower nibble
		byte |= hex_char_to_bin(hex[i + 1]);

		bin += (char)byte;
	}
	return bin;
}
```

With the above modifications, this line of code will produce the expected value `0xBE81`:
`std::cout << calcCRC(hex_str_to_bin_str(s), CRC::CRC_16_X25()) << std::endl;`

Note that the return value of `hex_char_to_bin` was changed to uint8_t.

**Comment by APayerl** [comment]
Thank you so much! Will try this today! 😀

**Comment by APayerl** [comment]
I tried it now, and it does indeed work, I'm so grateful!
One bonus question... do you have a neat way to change the endianness? :D

**Comment by d-bahr** [comment]
There's no built-in support in CRCpp for changing endianness, I'm afraid. One option is to loop through the array of data in increments of 2 or 4 bytes (or whatever your word size is) and swap the bytes around before calling `CRC::Calculate()`.

**Comment by APayerl** [comment]
Oh okay, thanks! 🙂

**Comment by APayerl** [comment]
@d-bahr 
So it looks like I'm still having issues....
I do this on a NodeMCU publishing the result to mqtt.
```
std::stringstream ss0;
CRC::Table<std::uint16_t, 16> table(CRC::CRC_16_X25());
std::string s = hex_str_to_bin_str("A11D01000110B0AEE6E7000F4000000000022409060100000281FF09074B464D5F30303109060000600100FF09103733343031353730333035343234373609060000600107FF09074D41333034483409060100010700FF060000000309060100020700FF060000000009060100030700FF060000000009060100040700FF0600000000090601001F0700FF060000002009060100330700FF060000000009060100470700FF060000000009060100200700FF060000091209060100340700FF060000000009060100480700FF060000000009060000010000FF090C07E5031702123200FFFFC40009060100010800FF060000047609060100020800FF060000000009060100030800FF060000004309060100040800FF0600000000");
ss0 << std::hex << CRC::Calculate(s.c_str(), s.length(), table);
client.publish("energy/crc/test", ss0.str().c_str());
```
The answer here becomes "6547".

Then I have a different test running on my pc:
```
std::string s = "A11D01000110B0AEE6E7000F4000000000022409060100000281FF09074B464D5F30303109060000600100FF09103733343031353730333035343234373609060000600107FF09074D41333034483409060100010700FF060000000309060100020700FF060000000009060100030700FF060000000009060100040700FF0600000000090601001F0700FF060000002009060100330700FF060000000009060100470700FF060000000009060100200700FF060000091209060100340700FF060000000009060100480700FF060000000009060000010000FF090C07E5031702123200FFFFC40009060100010800FF060000047609060100020800FF060000000009060100030800FF060000004309060100040800FF0600000000";
std::stringstream ss;
std::string c = hex_str_to_bin_str(s);
CRC::Table<std::uint16_t, 16> table(CRC::CRC_16_X25());
ss << std::hex << CRC::Calculate(c.c_str(), c.length(), table);
std::cout << ss.str() << std::endl;
```
which outputs "be81".... 
Could the result of CRC::Calculate differentiate between architectures?

**Comment by APayerl** [comment]
Would it be possible to do something like this?

```
std::string s = "A11D01000110B0AEE6E7000F4000000000022409060100000281FF09074B464D5F30303109060000600100FF09103733343031353730333035343234373609060000600107FF09074D41333034483409060100010700FF060000000309060100020700FF060000000009060100030700FF060000000009060100040700FF0600000000090601001F0700FF060000002009060100330700FF060000000009060100470700FF060000000009060100200700FF060000091209060100340700FF060000000009060100480700FF060000000009060000010000FF090C07E5031702123200FFFFC40009060100010800FF060000047609060100020800FF060000000009060100030800FF060000004309060100040800FF0600000000";
std::vector<uint16_t> list;

for(int i = 0; (i + 1) < s.length(); i += 2) {
    std::stringstream ss;
    uint16_t goal;
    ss << std::hex << s.substr(i, 2);
    ss >> goal;
    list.push_back(goal);
}
CRC::Table<std::uint16_t, 16> table(CRC::CRC_16_X25());
uint16_t result = CRC::Calculate(list, list.size(), table);
std::cout << std::hex << result << std::endl;
```

**Comment by d-bahr** [comment]
Yes, that would be one way to do it. You may have to worry about endianness, but I think most compilers have intrinsics to help with that.

**Comment by d-bahr** [comment]
Everything appears to be resolved, so I'm going to close this issue for now. If you have further questions, feel free to reopen it.
