### ISSUE TITLE
Is there a Release 1.0.0.0 downloadable as .zip planned,

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [d-bahr/CRCpp#5]
where the fixes #3 and #4 and static_casts and -Wshift-count-overflow fixes are included?
Thanks.

**Comment by d-bahr** [comment]
I was waiting to hear back regarding #4 but that was a while ago, so I will assume the fix is good.

Created a release-1.0.0.0 tag:
https://github.com/d-bahr/CRCpp/releases/tag/release-1.0.0.0
